services:
  postgresql:
    image: postgres:16.3
    container_name: hs-pg
    ports:
      - "65432:5432"
    volumes:
      - postgresql-hs-local:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    logging:
      options:
        max-size: 100m
        max-file: "5"
    networks:
      - hs
  
  server:
    build: 
      context: ../house_search_api/
      dockerfile: ../house_search_api/Dockerfile
    container_name: hs-server
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - postgresql
    networks:
      - hs
  
  ui:
    build:
      context: ../house_search_ui/
      dockerfile: ../house_search_ui/Dockerfile
    container_name: hs-ui
    ports:
      - "3002:3000"
    env_file:
      - .env
    networks:
      - hs

networks:
  hs:
    driver: bridge

volumes:
  postgresql-hs-local:
    driver: local
